backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
#publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/research/research.md"
        label: "Research Explorer"
        name: "research"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "research"}
          - {label: "Path", name: "path", widget: "hidden", default: "/research"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
  - name: "citations"
    label: "Citations"
    folder: "src/data/citations"
    create: false
    delete: true
    format: yaml
    fields:
      - { name: pmid, label: "Pubmed ID", widget: hidden }
      - { name: categories, label: Categories, widget: list, fields: [{label: Enabled, name: enabled, widget: boolean}, {label: Name, name: name, widget: select, options: ["Symptoms", "Diagnosis", "Case Studies", "Prevalence", "Genetics", "Physiopathology", "Biochemistry", "Therapies"]}]}
      - { name: title, label: Title, widget: hidden }
      - { name: abstract, label: Abstract, widget: hidden }
      - { name: abstractLink, label: Abstract Link, widget: hidden }
      - { name: fullTextLink, label: Full Text Link, widget: hidden }
      - { name: date, label: Date, widget: hidden }
      - { name: authors, label: Authors, widget: hidden, fields: [{label: Name, name: name, widget: string}]}
      - { name: keywords, label: Keywords, widget: hidden, fields: [{label: Keyword, name: keyword, widget: string}]}
      - { name: cites, label: Cites, widget: hidden, fields: [{label: PMID, name: pmid, widget: string}]}
      - { name: citedBy, label: Cited By, widget: hidden, fields: [{label: PMID, name: pmid, widget: string}]}
